# 站点设置
title: 原田莓莓
tagline: 王者自由
author:
  name: Kingfree
  email: kingfree@toyama.moe
  gitlab: "http://git.kingfree.moe"
  github: kingfree
  weibo: kingfree
  twitter: kingfreet
  qq: 947925753
baseurl: ""
url: "http://blog.kingfree.moe"
production_url: "http://blog.kingfree.moe"

plugins_dir: _plugins

# 构建设置
exclude: ["vendor"]
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

# 评论插件
JB:
  version : 0.3.0
  ASSET_PATH: /assets
  tags_path : /tags/
  atom_path : /atom.xml
  rss_path : /rss.xml
  comments:
    provider : uyan
    uyan:
      uid: 2132897
    duoshuo :
      short_name : kingfree

exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - .idea
