# 站点设置
title: 咲衣憧
tagline: 王者自由
author:
  name: Kingfree
  email: anytjf@live.com
  gmail: anytjf@gmail.com
  github: kingfree
  weibo: kingfree
baseurl: ""
url: "http://kingfree.github.io"
production_url: "http://kingfree.github.io"

# 构建设置
markdown: kramdown
highlighter: pygments
