# 站点设置
title: 咲衣憧
subtitle: 王者自由
email: anytjf@live.com
description: >
  萌豚，声豚，大友，非提，非P；博爱，喜轻百合；天麻厨，东山厨，阿澄蜜。
baseurl: ""
url: "http://kingfree.github.io"
weibo_username: kingfree
github_username:  kingfree

# 构建设置
markdown: kramdown
highlighter: pygments
