# 站点设置
title: 咲衣憧
tagline: 王者自由
author:
  name: Kingfree
  email: anytjf@live.com
  gmail: anytjf@gmail.com
  github: kingfree
  weibo: kingfree
baseurl: ""
url: "http://blog.kingfree.moe"
production_url: "http://blog.kingfree.moe"

# 构建设置
exclude: ["vendor"]
markdown: kramdown
highlighter: rouge

# 评论插件
JB:
  version : 0.3.0

  BASE_PATH : http://kingfree.github.io

  tags_path : /tags/
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : duoshuo
    duoshuo :
      short_name : kingfree
